VERBOSE: True

MODEL:
  SESSION: 'RDD'
  INPUT: 'input'
  TARGET: 'target'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 1
  NUM_EPOCHS: 300
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  SEED: 3407
  WANDB: False

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  PS_W: 512
  PS_H: 512
  TRAIN_DIR: '../dataset/RDD/train/' # path to training data
  VAL_DIR: '../dataset/RDD/test/'     # path to validation data
  SAVE_DIR: './checkpoints/'          # path to save models and images

TESTING:
  WEIGHT: './checkpoints/best.pth'
  SAVE_IMAGES: True